-- ====================================================================
-- WATER INTELLIGENCE: DATABASE SCHEMA (MVP)
-- Prepared for Smart India Hackathon
-- Module Owner: Akansha (Database & Data Management)
-- ====================================================================

-- 1. REGIONS / LOCATION METADATA
-- Stores state, district, city, coordinates and baseline population
CREATE TABLE IF NOT EXISTS regions (
    region_id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    latitude REAL,
    longitude REAL,
    baseline_population INTEGER
);

-- 2. WEATHER & RAINFALL OBSERVATIONS
-- Daily rainfall (mm), moving averages, deviation from normal, and temperatures
CREATE TABLE IF NOT EXISTS weather_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    region_id VARCHAR(10) NOT NULL REFERENCES regions(region_id),
    date DATE NOT NULL,
    rainfall_mm REAL DEFAULT 0.0,
    rainfall_7d_avg REAL,
    rainfall_deviation_pct REAL,
    temperature_c REAL,
    humidity_pct REAL,
    data_quality_score REAL DEFAULT 1.0,
    UNIQUE(region_id, date)
);

-- 3. WATER AVAILABILITY OBSERVATIONS
-- Reservoir storage capacity %, groundwater level depth (meters), and supply capacity (MLD)
CREATE TABLE IF NOT EXISTS water_availability (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    region_id VARCHAR(10) NOT NULL REFERENCES regions(region_id),
    date DATE NOT NULL,
    reservoir_level_pct REAL,
    groundwater_depth_m REAL,
    storage_capacity_mld REAL,
    water_trend VARCHAR(20) DEFAULT 'STABLE', -- 'DECLINING', 'STABLE', 'IMPROVING'
    UNIQUE(region_id, date)
);

-- 4. WATER CONSUMPTION & DEMAND
-- Daily municipal usage in Million Liters per Day (MLD) and per capita usage
CREATE TABLE IF NOT EXISTS water_consumption (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    region_id VARCHAR(10) NOT NULL REFERENCES regions(region_id),
    date DATE NOT NULL,
    daily_usage_mld REAL,
    per_capita_usage_lpcd REAL,
    demand_trend VARCHAR(20) DEFAULT 'STABLE', -- 'INCREASING', 'STABLE', 'DECREASING'
    UNIQUE(region_id, date)
);

-- 5. AI / ML PREDICTIONS & EARLY WARNING ALERTS
-- Output generated by the AI/ML layer for risk scoring and dashboard alerts
CREATE TABLE IF NOT EXISTS prediction_alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    region_id VARCHAR(10) NOT NULL REFERENCES regions(region_id),
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    current_status VARCHAR(20) NOT NULL,    -- 'LOW', 'MODERATE', 'HIGH', 'CRITICAL'
    water_trend VARCHAR(20) NOT NULL,       -- 'DECLINING', 'STABLE', 'IMPROVING'
    forecast_7d VARCHAR(20) NOT NULL,       -- 'DECREASING', 'STABLE', 'INCREASING'
    forecast_today_pct REAL NOT NULL,
    forecast_day2_pct REAL NOT NULL,
    forecast_day3_pct REAL NOT NULL,
    forecast_day4_pct REAL NOT NULL,
    alert_title VARCHAR(200) NOT NULL,
    main_factors TEXT NOT NULL,             -- JSON string or comma-separated factors
    action_recommendation TEXT NOT NULL,
    is_active INTEGER DEFAULT 1
);

-- Indexing for fast queries by region and date (prevents slow queries on time series)
CREATE INDEX IF NOT EXISTS idx_weather_region_date ON weather_metrics(region_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_avail_region_date ON water_availability(region_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_cons_region_date ON water_consumption(region_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_region ON prediction_alerts(region_id, generated_at DESC);
